#apiVersion: v1
#kind: Service
#metadata:
#  name: demo
#spec:
#  type: NodePort
#  selector:
#    app: demo
#  ports:
#  - port: 3000
#    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-demo-$VER
  labels:
    app: demo
    version: $VER
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: $VER
    spec:
      containers:
      - name: demo
        image: $IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000